import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { api } from "../api";

export default function AISummaryPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [summary, setSummary] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string>("");

  useEffect(() => {
    if (!id) return;
    api.ai.getSummary(id)
      .then((res) => {
        setSummary(res.summary);
      })
      .catch((err) => {
        console.error(err);
        setError("Failed to load patient summary. The backend AI service might have encountered an issue.");
      })
      .finally(() => setLoading(false));
  }, [id]);

  // A very simple markdown parser for bold, headers, and bullets
  const parseMarkdown = (text: string) => {
    return text.split("\n").map((line, idx) => {
      let formattedLine = line;
      
      // Headers
      if (formattedLine.startsWith("### ")) {
        return <h3 key={idx} className="text-lg font-bold mt-4 mb-2 text-slate-800 dark:text-slate-200">{formattedLine.replace("### ", "")}</h3>;
      }
      if (formattedLine.startsWith("## ")) {
        return <h2 key={idx} className="text-xl font-bold mt-5 mb-3 text-slate-900 border-b pb-2 border-slate-200">{formattedLine.replace("## ", "")}</h2>;
      }
      if (formattedLine.startsWith("# ")) {
        return <h1 key={idx} className="text-2xl font-black mt-6 mb-4 brand-gradient bg-clip-text text-transparent">{formattedLine.replace("# ", "")}</h1>;
      }
      
      // Bolds - handle inline markdown simple replacement
      const boldParts = formattedLine.split(/\*\*(.*?)\*\*/g);
      
      return (
        <p key={idx} className="mb-2 text-slate-700 leading-relaxed max-w-3xl">
          {boldParts.map((part, i) => i % 2 === 1 ? <strong key={i} className="font-semibold text-slate-900 dark:text-white">{part}</strong> : part)}
        </p>
      );
    });
  };

  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto min-h-screen">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-black tracking-tight text-slate-900 dark:text-white mb-2">VisiCare AI Integration</h1>
          <p className="text-slate-500">Comprehensive patient overview generated by Gemini 2.5</p>
        </div>
        <button
          onClick={() => navigate(-1)}
          className="px-4 py-2 border border-slate-200 rounded-xl hover:bg-slate-50 transition-colors dark:border-slate-700 dark:hover:bg-slate-800"
        >
          &larr; Back
        </button>
      </div>

      <div className="glass-card rounded-3xl p-8 mb-8">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-cyan-400 to-blue-500 flex items-center justify-center text-white p-2 shadow-lg shadow-cyan-200">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <h2 className="text-xl font-bold">Patient Intelligent Summary</h2>
        </div>

        {loading ? (
          <div className="flex flex-col items-center justify-center py-20">
            <div className="w-12 h-12 border-4 border-cyan-100 border-t-cyan-500 rounded-full animate-spin mb-4"></div>
            <p className="text-slate-500 animate-pulse">Analyzing clinical records and generating summary...</p>
          </div>
        ) : error ? (
          <div className="bg-rose-50 border border-rose-200 text-rose-700 p-4 rounded-xl">
            {error}
          </div>
        ) : (
          <div className="prose prose-slate max-w-none">
            {parseMarkdown(summary)}
          </div>
        )}
      </div>
      
      {!loading && !error && (
        <div className="flex justify-center">
          <button 
            onClick={() => navigate(`/family/dashboard/ai-chat/${id}`)}
            className="action-primary px-8 py-4 rounded-2xl font-bold tracking-wide flex items-center gap-3"
          >
            Ask Questions About This Patient
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
               <path fillRule="evenodd" d="M18 10c0 3.866-3.582 7-8 7a8.841 8.841 0 01-4.083-.98L2 17l1.338-3.123C2.493 12.767 2 11.434 2 10c0-3.866 3.582-7 8-7s8 3.134 8 7zM7 9H5v2h2V9zm8 0h-2v2h2V9zM9 9h2v2H9V9z" clipRule="evenodd" />
            </svg>
          </button>
        </div>
      )}
    </div>
  );
}
